language: ruby
rvm:
- 2.0
script:
- rake setup
after_script:
- rake autodeploy
env:
  global:
  - secure: "Gfz3Y4s2SF/Lr64qoce+CvpYxD0TiJbL1YQv6t+/z5nWUyoL8E6iXnRaY0/o3vgl8+/2Go+m197DYgm4tO7NdGg7XECU8XMM4zbBzkjyy5nmAFGF4Y2OTEA7aViwMMZOtb/MqvLddM6n7n3XkN4XQBf+wchVOCJIfk8gki8g1/4="

