title: Hack Your Design!
author: Toshimaru
pygments: true
production: false
paginate : 5
permalink: /:title/

exclude: Rakefile, Gemfile, Gemfile.lock, README.md

# tagging
tag_page_layout: tag_page
tag_page_dir: tag
