title: Hack Your Design!
author: Toshimaru
paginate: 14
permalink: /:title/
exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, vendor]
sass:
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-toc
  - jekyll/tagging
  - jemoji
  - jekyll-paginate

fqdn: blog.toshimaru.net
url: http://blog.toshimaru.net
description: toshimaruの技術系なブログ

# tagging
tag_page_layout: tag_page
tag_page_dir: tag

# my extra information
info: "Web Developer @Gunosy. カナダ・バンクーバーでの修行時代を経て日本帰国。最近はもっぱらRuby on Railsと奮闘する日々。ブログでは技術ネタをよく書いています。"
mail: me@toshimaru.net

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      og_type: blog
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      og_type: article
