title: Hack Your Design!
author: Toshimaru
paginate: 14
permalink: /:title/
exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, vendor, deploy.bash]
timezone: Japan
sass:
  style: :compressed
gems:
  - jemoji
  - jekyll/tagging
  - jekyll-toc
  - jekyll-tagging-related_posts
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-coffeescript
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      og_type: blog
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      og_type: article
feed:
  path: atom.xml

fqdn: blog.toshimaru.net
url: http://blog.toshimaru.net
mail: me@toshimaru.net
description: toshimaruの技術系なブログ
info: "Web Developer @Gunosy. カナダ・バンクーバーでの修行時代を経て日本帰国。最近はもっぱらRuby on Railsと奮闘する日々。ブログでは技術ネタをよく書いています。"

# tagging
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
