title: Hack Your Design!
author: Toshimaru
paginate : 9
permalink: /:title/
exclude: [Rakefile, Gemfile, Gemfile.lock, README.md]
sass:
  style: :compressed

gems:
  - jekyll-sitemap

fqdn: blog.toshimaru.net
url: http://blog.toshimaru.net
description: toshimaruの技術系なブログ

# tagging
tag_page_layout: tag_page
tag_page_dir: tag

# my extra information
info: "Web Developer. 現在カナダのバンクーバにて修行中。技術ネタをよく書いてます。最近興味あるのはRoRとフロントエンド関連技術。"
mail: me@toshimaru.net

# want to use yui, but there is a bug.
# ref. https://github.com/yui/yuicompressor/issues/113
assets:
  css_compressor: ~

# default set to post, but seems buggy
# defaults:
#   -
#     scope:
#       path: "" # empty string for all files
#     values:
#       layout: "post"
