title: Hack Your Design!
author: Toshimaru
paginate : 9
permalink: /:title/
exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, vendor]
sass:
  style: :compressed

gems:
  - jekyll-sitemap

fqdn: blog.toshimaru.net
url: http://blog.toshimaru.net
description: toshimaruの技術系なブログ

# tagging
tag_page_layout: tag_page
tag_page_dir: tag

# my extra information
info: "Web Developer @ Gunosy. カナダ・バンクーバでの修行時代を経て日本帰国。技術ネタをよく書きます。最近興味あるのはRoRとフロントエンド関連技術。"
mail: me@toshimaru.net
