title: Hack Your Design!
author: Toshimaru
pygments: true
production: false
paginate : 9
permalink: /:title/
exclude:
- Rakefile
- Gemfile
- Gemfile.lock
- README.md

fqdn: blog.toshimaru.net
url: http://blog.toshimaru.net
description: toshimaruの技術系なブログ

# tagging
tag_page_layout: tag_page
tag_page_dir: tag

# use another markdown renderer
markdown: kramdown

# my information
info: "Web Developer. 現在カナダのバンクーバにて修行中。技術ネタをよく書いてます。最近興味あるのはRoRとフロントエンド関連技術。"
mail: me@toshimaru.net

assets:
  css_compressor: yui
