title: Hack Your Design!
author: Toshimaru
pygments: true
production: false
paginate : 8
permalink: /:title/
exclude: 
- Rakefile
- Gemfile
- Gemfile.lock
- README.md

url: http://blog.toshimaru.net
description: toshimaruの技術系なブログ

# tagging
tag_page_layout: tag_page
tag_page_dir: tag

# use another markdown renderer
markdown: kramdown
